# This GitHub actions was inspired from
# https://github.com/plippe/breathe/blob/main/.github/workflows/deploy-github-pages.yml

name: CD-CI Rust WASM

on:
  workflow_dispatch:
  push:
    branches:
      - main
    ignore-paths:
      - .gitattributes
      - .gitignore
      - LICENSE.md
      - README.md

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    name: Build & Deploy

    permissions:
      contents: write

    steps:
      - name: Checkout files
        uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: |
          cargo install trunk || true \
            && rustup target add wasm32-unknown-unknown

      - name: Build the Rust WASM app and all of its assets
        run: trunk build --public-url ${{ github.event.repository.name }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          folder: dist
